### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [ueffel/Reminder#1]
Dear Steffen,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by ueffel** [comment]
Everyone who has .Net Framework installed, has the `csc.exe` compiler. Without the framework the app wouldn't run anyway.
Besides this is a just-for-fun project I don't intend to maintain actively or expect anyone to use.

**Comment by sergeevabc** [comment]
Indeed, I have .Net Framework 4 installed and tried all commands you listed in readme.md.
However ```csc``` throws error as follows, that’s why I created this issue.
![][1]

It should be relatively easy for you to upload ```.exe``` here, right? 

[1]: https://vgy.me/tGdmtT.png

**Comment by ueffel** [comment]
Curious. I wonder what the compiler says in the command line. At any rate, here:
https://www.dropbox.com/s/3qrlvnaxa09ds8v/reminder.zip?dl=0

**Comment by sergeevabc** [comment]
Thank you, Steffen. It works.

Since no details about error were found in command-line output, I started digging and found [similar report][1], which led me to the [explanation][2]: in brief, codepage should be changed before compilation.
``

[1]: http://stackoverflow.com/q/30905746
[2]: http://stackoverflow.com/questions/30956834/why-is-csc-exe-crashing-when-i-last-left-the-output-encoding-as-utf8

**Comment by sergeevabc** [comment]
Well, eventually I’m not happy with it, since command-line windows hangs after reminder is created.

**Comment by ueffel** [comment]
I never had problems with my command line. I'm using the default code page for german windows which is 850 `chcp 850`. Well have it you way, use you little script.
